### ISSUE TITLE
data-folder missing?

### ISSUE THREAD

**Issue by coderofsalvation** [kosowski/SimplePBR#3]
![Screenshot from 2019-09-23 15-50-49](https://user-images.githubusercontent.com/180068/65431556-f6f04180-de19-11e9-8063-8a55104ecdeb.png)

I checked the zips in the releases section, but didn't really find the `data`-folder with the `integratedbrdf.png` file in it. 
Forgot to include?

Btw. is it crazy to assume this might work in android as well?
I mean almost everything has a dedicated gpu these days..

**Comment by kosowski** [comment]
The data folder with the brdf map is included in the jar file, might be related to the Android mode?

I don´t expect it to work on Android, this is very barebones and highly inefficient. Google´s Filament would be a better starting point for Android.
