### ISSUE TITLE
box() not as reflective as sphere() ?

### ISSUE THREAD

**Issue by danieltorrer** [kosowski/SimplePBR#5]
Maybe not an issue but on the materials demo I changed `sphere()` for `box()` and the latter doesn't look as reflective as the first one. 

Both have the same amount of `roughness` and `metallic`. How can I achieve the same effect for both?

![frame244](https://user-images.githubusercontent.com/2329316/78817206-20964200-79d3-11ea-97bf-4850268f1eba.png)
![frame286](https://user-images.githubusercontent.com/2329316/78817237-2db33100-79d3-11ea-8f20-93eb7d53c87e.png)

**Comment by kosowski** [comment]
I thinks this is perceptual: with a sphere you see almost half of the reflection cubemap, while with a box you see a small portion of it.
