### ISSUE TITLE
Error: Cannot compile fragment shader

### ISSUE THREAD

**Issue by agrshch** [kosowski/SimplePBR#7]
Hi!
I'm getting these errors when trying to run the examples:

OpenGL error 1280 at top endDraw(): invalid enumerant
RuntimeException: Cannot compile fragment shader:
ERROR: 0:167: Invalid call of undeclared identifier ‘texture2D’
ERROR: 0:174: Invalid call of undeclared identifier ‘texture2D’
ERROR: 0:180: Invalid call of undeclared identifier ‘texture2D’
ERROR: 0:187: Use of undeclared identifier ‘base’
ERROR: 0:187: Use of undeclared identifier ‘metallic’
ERROR: 0:204: Use of undeclared identifier ‘roughness’
ERROR: 0:205: Use of undeclared identifier ‘mipLevel’
ERROR: 0:266: Use of undeclared identifier ‘specular’
ERROR: 0:267: Use of undeclared identifier ‘specfresnel’
ERROR: 0:267: Use of undeclared identifier ‘roughness’
ERROR: 0:270: Use of undeclared identifier ‘specref’
ERROR: 0:273: Use of undeclared identifier ‘specfresnel’
ERROR: 0:280: Use of undeclared identifier ‘specref’
ERROR: 0:281: Use of undeclared identifier ‘diffref’
ERROR: 0:285: Use of undeclared identifier ‘roughness’
ERROR: 0:286: Use of undeclared identifier ‘specular’
ERROR: 0:286: Use of undeclared identifier ‘brdf’
ERROR: 0:286: Use of undeclared identifier ‘brdf’
ERROR: 0:288: Use of undeclared identifier ‘iblspec’
ERROR: 0:288: Use of undeclared identifier ‘envspec’
ERROR: 0:292: Use of undeclared identifier ‘base’
ERROR: 0:292: Use of undeclared identifier ‘metallic’
ERROR: 0:295: Use of undeclared identifier ‘result’
ERROR: 0:295: Use of undeclared identifier ‘result’
ERROR: 0:296: Use of undeclared identifier ‘result’

I use MacOS Catalina 10.15.7, 
Graphics:
AMD Radeon Pro 5500M 4 GB
Intel UHD Graphics 630 1536 MB

**Comment by kosowski** [comment]
Hi! Had some problems with MacOS, could you paste the full Processing console output, as some important messages are printed there before the error?

**Comment by agrshch** [comment]
Hi! Sure:

	0   AppKit                              0x00007fff2b5c0c59 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 371
	1   AppKit                              0x00007fff2b5a8682 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
	2   AppKit                              0x00007fff2b5a80f3 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	3   libnativewindow_macosx.jnilib       0x000000014bd293fe Java_jogamp_nativewindow_macosx_OSXUtil_CreateNSWindow0 + 398
	4   ???                                 0x0000000112706a88 0x0 + 4604324488
)
SimplePBR 0.1 by Nacho Cossio (@nacho_cossio) @ http://nachocossio.com
OpenGL error 1280 at top endDraw(): invalid enumerant
RuntimeException: Cannot compile fragment shader:
ERROR: 0:167: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:174: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:180: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:187: Use of undeclared identifier 'base'
ERROR: 0:187: Use of undeclared identifier 'metallic'
ERROR: 0:204: Use of undeclared identifier 'roughness'
ERROR: 0:205: Use of undeclared identifier 'mipLevel'
ERROR: 0:266: Use of undeclared identifier 'specular'
ERROR: 0:267: Use of undeclared identifier 'specfresnel'
ERROR: 0:267: Use of undeclared identifier 'roughness'
ERROR: 0:270: Use of undeclared identifier 'specref'
ERROR: 0:273: Use of undeclared identifier 'specfresnel'
ERROR: 0:280: Use of undeclared identifier 'specref'
ERROR: 0:281: Use of undeclared identifier 'diffref'
ERROR: 0:285: Use of undeclared identifier 'roughness'
ERROR: 0:286: Use of undeclared identifier 'specular'
ERROR: 0:286: Use of undeclared identifier 'brdf'
ERROR: 0:286: Use of undeclared identifier 'brdf'
ERROR: 0:288: Use of undeclared identifier 'iblspec'
ERROR: 0:288: Use of undeclared identifier 'envspec'
ERROR: 0:292: Use of undeclared identifier 'base'
ERROR: 0:292: Use of undeclared identifier 'metallic'
ERROR: 0:295: Use of undeclared identifier 'result'
ERROR: 0:295: Use of undeclared identifier 'result'
ERROR: 0:296: Use of undeclared identifier 'result'

**Comment by agrshch** [comment]
Now I see that I use version 0.1 meanwhile the latest is 0.3.
After switching to 0.3 everything works, no errors. Sorry to bother you.
Probably you should update the link to this library on the Processing forum. This is where I got the 0.1 version :) https://discourse.processing.org/t/simplepbr-physically-based-rendering-library/23077

Thank you!

**Comment by kosowski** [comment]
You are right,  my website links to the 0.1 release. It has now been updated, thanks for pointing that out.
Glad is now working for you. Please let me know if you post something done with it, would like to see :)
Best wishes!
